name: hostreamly-docker
services:
- name: backend-api
  image:
    registry_type: DOCR
    repository: hostreamly-backend
    tag: latest
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 3000
  routes:
  - path: /api
  envs:
  - key: NODE_ENV
    value: production
  - key: DO_SPACES_KEY
    value: DO00WBENZMAW6MK9F2FU
  - key: DO_SPACES_SECRET
    value: ry8YjODcKpv/leqbHcUj1lYP5C4G+UtLc6tPOGOtGqg
  - key: DO_SPACES_BUCKET
    value: hostreamly
  - key: DO_SPACES_REGION
    value: sfo3
  - key: DO_SPACES_ENDPOINT
    value: https://hostreamly.sfo3.digitaloceanspaces.com
- name: frontend
  image:
    registry_type: DOCR
    repository: hostreamly-frontend
    tag: latest
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 80
  routes:
  - path: /
databases:
- engine: PG
  name: hostreamly-db
  num_nodes: 1
  size: db-s-dev-database
  version: "15"