# DigitalOcean App Platform Configuration for Hostreamly
name: hostreamly-platform
services:
  # Backend API Service
  - name: backend-api
    github:
      repo: hostreamly/hostreamly
      branch: main
    source_dir: /backend
    run_command: npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8080
    
    # Environment Variables for Backend
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "8080"
      - key: JWT_SECRET
        type: SECRET
        value: "your-jwt-secret-here"
      - key: DATABASE_URL
        type: SECRET
        value: "${hostreamly-db.DATABASE_URL}"
      # REDIS_URL removed - Redis not available in basic plan
      
      # DigitalOcean Spaces Configuration
      - key: DO_SPACES_KEY
        type: SECRET
        value: "your-spaces-access-key"
      - key: DO_SPACES_SECRET
        type: SECRET
        value: "your-spaces-secret-key"
      - key: DO_SPACES_BUCKET
        value: "your-space-name"
      - key: DO_SPACES_REGION
        value: "nyc3"
      - key: DO_SPACES_ENDPOINT
        value: "https://nyc3.digitaloceanspaces.com"
      
      # Bunny.net Configuration (if still using)
      - key: BUNNY_API_KEY
        type: SECRET
        value: "your-bunny-api-key"
      - key: BUNNY_STORAGE_ZONE
        value: "your-bunny-storage-zone"
      
    # Health check
    health_check:
      http_path: /api/health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

  # Routes configuration for backend
    routes:
      - path: /api
        preserve_path_prefix: true

# Database Configuration
databases:
  - name: hostreamly-db
    engine: PG
    version: "13"
    size: basic-xs
    num_nodes: 1
# Redis removed - requires production plan
# Can be added later when upgrading to production

# Static Sites Configuration
static_sites:
  - name: frontend
    github:
      repo: hostreamly/hostreamly
      branch: main
    source_dir: /
    build_command: npm run build
    output_dir: /dist
    routes:
      - path: /
        preserve_path_prefix: false

# Domain configuration (optional)
# domains:
#   - domain: your-domain.com
#     type: PRIMARY
#   - domain: www.your-domain.com
#     type: ALIAS

# Alerts configuration removed - not supported at app level
# Can be configured later through DigitalOcean dashboard