# DigitalOcean App Platform Configuration for Hostreamly
name: hostreamly-unified
services:
- name: backend
  source_dir: /apps/backend
  github:
    repo: jorgekof/hostreamly
    branch: main
  run_command: node server.js
  build_command: npm install
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "8080"
  - key: DATABASE_URL
    value: ${db.DATABASE_URL}
  - key: BUNNY_API_KEY
    value: ${BUNNY_API_KEY}
  - key: BUNNY_STORAGE_ZONE
    value: ${BUNNY_STORAGE_ZONE}
  - key: BUNNY_CDN_HOSTNAME
    value: ${BUNNY_CDN_HOSTNAME}
  - key: BUNNY_STORAGE_PASSWORD
    value: ${BUNNY_STORAGE_PASSWORD}
  - key: BUNNY_STREAM_API_KEY
    value: ${BUNNY_STREAM_API_KEY}
  - key: BUNNY_STREAM_LIBRARY_ID
    value: ${BUNNY_STREAM_LIBRARY_ID}
  - key: BUNNY_STREAM_CDN_HOSTNAME
    value: ${BUNNY_STREAM_CDN_HOSTNAME}
  - key: BUNNY_STREAM_COLLECTION_ID
    value: ${BUNNY_STREAM_COLLECTION_ID}
  - key: BUNNY_STREAM_WEBHOOK_SECRET
    value: ${BUNNY_STREAM_WEBHOOK_SECRET}
  - key: SPACES_KEY
    value: ${SPACES_KEY}
  - key: SPACES_SECRET
    value: ${SPACES_SECRET}
  - key: SPACES_ENDPOINT
    value: ${SPACES_ENDPOINT}
  - key: SPACES_BUCKET
    value: ${SPACES_BUCKET}
  - key: SPACES_REGION
    value: ${SPACES_REGION}
  - key: JWT_SECRET
    value: ${JWT_SECRET}
  - key: ENCRYPTION_KEY
    value: ${ENCRYPTION_KEY}
  - key: ADMIN_EMAIL
    value: ${ADMIN_EMAIL}
  - key: ADMIN_PASSWORD
    value: ${ADMIN_PASSWORD}
  - key: SMTP_HOST
    value: ${SMTP_HOST}
  - key: SMTP_PORT
    value: ${SMTP_PORT}
  - key: SMTP_USER
    value: ${SMTP_USER}
  - key: SMTP_PASS
    value: ${SMTP_PASS}
  - key: REDIS_URL
    value: ${REDIS_URL}
  - key: AGORA_APP_ID
    value: ${AGORA_APP_ID}
  - key: AGORA_APP_CERTIFICATE
    value: ${AGORA_APP_CERTIFICATE}
  - key: STRIPE_SECRET_KEY
    value: ${STRIPE_SECRET_KEY}
  - key: STRIPE_WEBHOOK_SECRET
    value: ${STRIPE_WEBHOOK_SECRET}
  - key: PAYPAL_CLIENT_ID
    value: ${PAYPAL_CLIENT_ID}
  - key: PAYPAL_CLIENT_SECRET
    value: ${PAYPAL_CLIENT_SECRET}
  - key: PAYPAL_WEBHOOK_ID
    value: ${PAYPAL_WEBHOOK_ID}
  - key: OPENAI_API_KEY
    value: ${OPENAI_API_KEY}
  - key: GOOGLE_CLOUD_PROJECT_ID
    value: ${GOOGLE_CLOUD_PROJECT_ID}
  - key: GOOGLE_CLOUD_KEY_FILE
    value: ${GOOGLE_CLOUD_KEY_FILE}
  - key: AWS_ACCESS_KEY_ID
    value: ${AWS_ACCESS_KEY_ID}
  - key: AWS_SECRET_ACCESS_KEY
    value: ${AWS_SECRET_ACCESS_KEY}
  - key: AWS_REGION
    value: ${AWS_REGION}
  - key: AWS_S3_BUCKET
    value: ${AWS_S3_BUCKET}
  - key: CLOUDFLARE_API_TOKEN
    value: ${CLOUDFLARE_API_TOKEN}
  - key: CLOUDFLARE_ZONE_ID
    value: ${CLOUDFLARE_ZONE_ID}
  - key: CLOUDFLARE_ACCOUNT_ID
    value: ${CLOUDFLARE_ACCOUNT_ID}
  health_check:
    http_path: /health
    initial_delay_seconds: 30
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3
  routes:
  - path: /api

# Database Configuration
databases:
  - name: hostreamly-db
    engine: PG
    version: "13"
    size: basic-xs
    num_nodes: 1
# Redis removed - requires production plan
# Can be added later when upgrading to production

# Static Sites Configuration
static_sites:
  - name: hostreamly-frontend
    source_dir: /apps/frontend
    github:
      repo: jorgekof/hostreamly
      branch: main
      deploy_on_push: true
    build_command: npm install && npm run build
    output_dir: dist
    environment_slug: node-js
    envs:
      - key: NODE_ENV
        value: production
      - key: VITE_API_BASE_URL
        value: "/api"
      - key: VITE_WEBSOCKET_URL
        value: ""
      - key: VITE_APP_BASE_URL
        value: ""
      - key: VITE_BUNNY_CDN_URL
        value: "https://hostreamly.b-cdn.net"
      - key: VITE_DO_SPACES_URL
        value: "https://hostreamly.sfo3.digitaloceanspaces.com"
      - key: VITE_BUNNY_STREAM_API_KEY
        type: SECRET
        value: "test_api_key_placeholder"
      - key: VITE_BUNNY_STREAM_LIBRARY_ID
        value: "test_library_id"
      - key: VITE_BUNNY_STREAM_BASE_URL
        value: "https://video.bunnycdn.com"
      - key: VITE_BUNNY_CDN_HOSTNAME
        value: "test_cdn_hostname"
      - key: VITE_BUNNY_PULL_ZONE
        value: "test_pull_zone"
      - key: VITE_BUNNY_STORAGE_ZONE
        value: "test_storage_zone"
      - key: VITE_NODE_ENV
        value: "production"
      - key: VITE_DEBUG_MODE
        value: "false"
    
    routes:
      - path: /
        preserve_path_prefix: false
    
    # Configuración de rutas para SPA
    catchall_document: index.html
    
    # Headers de seguridad - configurar en el servidor web

# Domain configuration (optional)
# domains:
#   - domain: your-domain.com
#     type: PRIMARY
#   - domain: www.your-domain.com
#     type: ALIAS

# Alerts configuration removed - not supported at app level
# Can be configured later through DigitalOcean dashboard