# DigitalOcean App Platform Configuration for Hostreamly
name: hostreamly-platform
services:
  # Backend API Service
  - name: backend-api
    source_dir: /backend
    github:
      repo: jorgekof/hostreamly
      branch: main
      deploy_on_push: true
    run_command: npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8080
    
    # Environment Variables for Backend
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "8080"
      - key: JWT_SECRET
        type: SECRET
        value: "JWT_H0str34mly_Sup3r_S3cr3t_K3y_Pr0d_2024_V3ry_L0ng_4nd_S3cur3"
      - key: DATABASE_URL
        type: SECRET
        value: "${hostreamly-db.DATABASE_URL}"
      
      # DigitalOcean Spaces Configuration
      - key: DO_SPACES_KEY
        type: SECRET
        value: "REEMPLAZAR_CON_TU_ACCESS_KEY"
      - key: DO_SPACES_SECRET
        type: SECRET
        value: "REEMPLAZAR_CON_TU_SECRET_KEY"
      - key: DO_SPACES_BUCKET
        value: "REEMPLAZAR_CON_TU_BUCKET_NAME"
      - key: DO_SPACES_REGION
        value: "nyc3"
      - key: DO_SPACES_ENDPOINT
        value: "https://nyc3.digitaloceanspaces.com"
      
      # Bunny.net Configuration
      - key: BUNNY_API_KEY
        type: SECRET
        value: "REEMPLAZAR_CON_TU_BUNNY_API_KEY"
      - key: BUNNY_STREAM_LIBRARY_ID
        value: "REEMPLAZAR_CON_TU_LIBRARY_ID"
      - key: BUNNY_STORAGE_ZONE
        value: "REEMPLAZAR_CON_TU_STORAGE_ZONE"
      - key: BUNNY_STORAGE_PASSWORD
        type: SECRET
        value: "REEMPLAZAR_CON_TU_STORAGE_PASSWORD"
      - key: BUNNY_PULL_ZONE
        value: "REEMPLAZAR_CON_TU_PULL_ZONE"
      - key: BUNNY_CDN_HOSTNAME
        value: "REEMPLAZAR_CON_TU_CDN_HOSTNAME"
      
    # Health check
    health_check:
      http_path: /api/health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

    # Routes configuration for backend
    routes:
      - path: /api
        preserve_path_prefix: true

# Database Configuration
databases:
  - name: hostreamly-db
    engine: PG
    version: "13"
    size: basic-xs
    num_nodes: 1
# Redis removed - requires production plan
# Can be added later when upgrading to production

# Static Sites Configuration
static_sites:
  - name: hostreamly-frontend
    source_dir: /frontend
    github:
      repo: jorgekof/hostreamly
      branch: main
      deploy_on_push: true
    build_command: |
      npm install
      npm run build
    environment_slug: node-js
    envs:
      - key: NODE_ENV
        value: production
      - key: VITE_API_BASE_URL
        value: "/api"
      - key: VITE_WEBSOCKET_URL
        value: ""
      - key: VITE_APP_BASE_URL
        value: ""
      - key: VITE_BUNNY_CDN_URL
        value: "https://hostreamly.b-cdn.net"
      - key: VITE_DO_SPACES_URL
        value: "https://hostreamly.sfo3.digitaloceanspaces.com"
      - key: VITE_BUNNY_STREAM_API_KEY
        type: SECRET
        value: "REEMPLAZAR_CON_TU_BUNNY_API_KEY"
      - key: VITE_BUNNY_STREAM_LIBRARY_ID
        value: "REEMPLAZAR_CON_TU_LIBRARY_ID"
      - key: VITE_BUNNY_STREAM_BASE_URL
        value: "https://video.bunnycdn.com"
      - key: VITE_BUNNY_CDN_HOSTNAME
        value: "REEMPLAZAR_CON_TU_CDN_HOSTNAME"
      - key: VITE_BUNNY_PULL_ZONE
        value: "REEMPLAZAR_CON_TU_PULL_ZONE"
      - key: VITE_BUNNY_STORAGE_ZONE
        value: "REEMPLAZAR_CON_TU_STORAGE_ZONE"
      - key: VITE_NODE_ENV
        value: "production"
      - key: VITE_DEBUG_MODE
        value: "false"
    
    routes:
      - path: /
        preserve_path_prefix: false
    
    # Configuración de rutas para SPA
    catchall_document: index.html
    
    # Headers de seguridad - configurar en el servidor web

# Domain configuration (optional)
# domains:
#   - domain: your-domain.com
#     type: PRIMARY
#   - domain: www.your-domain.com
#     type: ALIAS

# Alerts configuration removed - not supported at app level
# Can be configured later through DigitalOcean dashboard